name = "domain-management-system"
type = "pages"
workers_dev = true
compatibility_date = "2024-07-01"

[build]
command = "pnpm install --no-frozen-lockfile && pnpm build"
pages_build_output_dir = "dist/static"

[[redirects]]
source = "/*"
status = 200
destination = "/index.html"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    Surrogate-Control = "no-store"